import type { SiteContent } from "./types";

export const defaultContent: SiteContent = {
  home: {
    eyebrow: "ROBLOX CREATIVE LAB",
    title: "ZAYS",
    subtitle: "Tous mes projets Roblox au même endroit.",
    description: "Découvre mes jeux, mes scripts et mes futurs projets.",
    backgroundImage: "/images/hero-zays.webp",
    buttons: [
      { label: "Voir les jeux", target: "#jeux" },
      { label: "Voir les scripts", target: "#scripts" },
      { label: "Voir l’executor", target: "#executor" },
    ],
  },
  games: [
    {
      id: "redline-arena",
      name: "Redline Arena",
      description: "Une arène nerveuse où chaque déplacement compte. Maîtrise les lignes d’énergie et prends le contrôle du terrain.",
      image: "/images/game-arena.webp",
      banner: "/images/game-arena.webp",
      robloxUrl: "",
      status: "BETA",
      players: "Tests privés",
      buttonText: "Jouer",
      active: true,
    },
    {
      id: "neon-protocol",
      name: "Neon Protocol",
      description: "Infiltration, exploration et missions coopératives dans une mégalopole qui ne dort jamais.",
      image: "/images/game-neon-city.webp",
      banner: "/images/game-neon-city.webp",
      robloxUrl: "",
      status: "SOON",
      players: "En développement",
      buttonText: "Jouer",
      active: true,
    },
    {
      id: "project-zero",
      name: "Project Zero",
      description: "Un prototype mystérieux construit autour d’expériences courtes, intenses et rejouables.",
      image: "/images/hero-zays.webp",
      banner: "/images/hero-zays.webp",
      robloxUrl: "",
      status: "SOON",
      players: "Concept",
      buttonText: "Découvrir",
      active: true,
    },
  ],
  executor: {
    name: "ZAYS EXECUTOR",
    logo: "Z//",
    image: "/images/hero-zays.webp",
    description: "Un nouveau projet arrive bientôt. Plus d’informations prochainement.",
    status: "SOON",
    badgeText: "SOON",
    version: "0.1.0",
    estimatedDate: "À annoncer",
    buttonText: "COMING SOON",
    buttonUrl: "",
    visible: true,
  },
  scripts: [
    {
      id: "interface-kit",
      name: "Interface Kit",
      image: "UI",
      game: "Roblox Studio",
      description: "Composants d’interface accessibles et réutilisables pour accélérer le prototypage.",
      category: "GUI",
      updatedAt: "2026-08-08",
      content: "-- Exemple éducatif à adapter dans Roblox Studio\nprint(\"Zays Interface Kit chargé\")",
      status: "ACTIF",
      active: true,
    },
    {
      id: "fps-monitor",
      name: "Performance Monitor",
      image: "60",
      game: "Roblox Studio",
      description: "Petit outil de diagnostic pour suivre les performances pendant les tests en Studio.",
      category: "Utility",
      updatedAt: "2026-08-02",
      content: "-- Utilitaire de développement\nprint(\"Performance Monitor prêt\")",
      status: "ACTIF",
      active: true,
    },
    {
      id: "photo-mode",
      name: "Photo Mode",
      image: "◉",
      game: "Projets Zays",
      description: "Base créative pour préparer un mode photo dans tes propres expériences.",
      category: "Fun",
      updatedAt: "2026-07-24",
      content: "-- Démonstration sans fonction d’exploitation\nprint(\"Photo Mode en préparation\")",
      status: "ACTIF",
      active: true,
    },
  ],
  links: [
    { id: "discord", name: "Discord", image: "DC", description: "Serveur Discord officiel de Zays.", category: "Discord", url: "", updatedAt: "2026-08-14", status: "INACTIF", active: false },
    { id: "roblox", name: "Roblox", image: "RB", description: "Profil ou groupe Roblox officiel.", category: "Roblox", url: "", updatedAt: "2026-08-14", status: "INACTIF", active: false },
    { id: "youtube", name: "YouTube", image: "YT", description: "Chaîne YouTube officielle.", category: "YouTube", url: "", updatedAt: "2026-08-14", status: "INACTIF", active: false },
    { id: "tiktok", name: "TikTok", image: "TK", description: "Compte TikTok officiel.", category: "TikTok", url: "", updatedAt: "2026-08-14", status: "INACTIF", active: false },
    { id: "x", name: "X / Twitter", image: "X", description: "Compte X officiel.", category: "X", url: "", updatedAt: "2026-08-14", status: "INACTIF", active: false },
  ],
  bots: [],
  communityTitle: "Rejoins Zays",
  communityText: "Rejoins notre communauté pour recevoir les dernières nouveautés, annonces et mises à jour concernant les projets Zays.",
  communityButton: "REJOINDRE LE DISCORD",
  settings: {
    siteName: "Zays",
    logoText: "ZAYS",
    logoUrl: "",
    faviconUrl: "/favicon.svg",
    description: "Le hub officiel des projets Roblox Zays.",
    primaryColor: "#ff2435",
    backgroundColor: "#050506",
    textColor: "#ffffff",
    footerText: "© 2026 Zays. Tous droits réservés.",
  },
};
